name: ab_testing_firebase
description:
  Extends ab_testing_core to support remote A/B testing with Firebase Remote
  Config.
version: 0.11.0
repository: https://github.com/programmierbar/ab_testing
issue_tracker: https://github.com/programmierbar/ab_testing/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ab_testing_core: ^0.12.0+1
  firebase_core: ^2.0.0
  firebase_remote_config: ^3.0.0

dev_dependencies:
  lints: ^2.0.1
